---
# Source: wordpress-custom/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dry-run-wordpress-custom
  labels:
    helm.sh/chart: wordpress-custom-0.1.0
    app.kubernetes.io/name: wordpress-custom
    app.kubernetes.io/instance: dry-run
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: wordpress-custom
    app.kubernetes.io/instance: dry-run
---
# Source: wordpress-custom/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dry-run-wordpress-custom
  labels:
    helm.sh/chart: wordpress-custom-0.1.0
    app.kubernetes.io/name: wordpress-custom
    app.kubernetes.io/instance: dry-run
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress-custom
      app.kubernetes.io/instance: dry-run
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wordpress-custom
        app.kubernetes.io/instance: dry-run
    spec:
      securityContext:
        {}
      containers:
        - name: wordpress-custom
          securityContext:
            {}
          image: "wordpress:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {}
